---
apiVersion: v1
kind: Service
metadata:
  name: aks-poc
  namespace: default
spec:
  ports:
  - port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-poc
  namespace: default
  labels:
    app: aks-poc
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.node-web-app: semver:~1.0.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: aks-poc
  template:
    metadata:
      labels:
        app: aks-poc
    spec:
      containers:
      - name: aks-poc
        image: abinashkd/akspoc:37
        ports:
        - name: http
          containerPort: 8080